### ISSUE TITLE
Blend2D Kiva backend TODO

### ISSUE THREAD

**Issue by jwiggins** [enthought/enable#771]
The Kiva blend2d backend is still in a very alpha-quality state. Here's what we know is missing:

- [ ] Some of the graphics state needs to be tracked by the Kiva backend. (see instance attributes `path`, `font`, `_kiva_font`, `text_pos`, and `text_drawing_mode`)
- [ ] Only RGBA32 is supported right now. This might be the only [color] format supported by Blend2D.
- [ ] Not all CTM manipulations are supported
- [ ] Enable/Disable of anti-aliasing. Is it even possible?
- [ ] Line dashing
- [ ] `arc` and `arc_to` are incomplete/incosistent
- [ ] `get_path_bounding_box` returns an object which can't be introspected by the user because it's a thin wrapper around a C++ object.
- [ ] Most of the clipping functions aren't implemented
- [ ] `draw_image` doesn't yet handled `rect=None` as an argument. Also doesn't correctly handling flipping the image along the Y-axis
- [ ] `*_character_spacing` methods are not implemented
- [ ] `*_text_matrix` methods are not implemented
- [ ] Not all text drawing modes are implemented
- [ ] `get_text_extent` is not implemented
- [ ] `eof_fill_path` and EOF filling rule is not implemented
- [ ] `draw_path_at_points`/`draw_marker_at_points` not implemented
